services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
  fetcher:
    build:
      context: ./fetcher
      dockerfile: mqtt_client.Dockerfile
    volumes:
      - ../cache/fetch:/fetch
    depends_on:
      - mosquitto
  runner:
    build: ./runner
    volumes:
      - ../workflow.yaml:/app/workflow.yaml
    depends_on:
      - fetcher
