services:
  mosquitto:
    build: ./mosquitto
    ports:
      - 1883:1883
    volumes:
      - ..cache/log/mosquitto:/mosquitto/log
  fetcher:
    build: ./fetcher
    volumes:
      - ../cache/fetch:/fetch
    depends_on:
      - mosquitto
  runner:
    build: ./runner
    volumes:
      - ../workflow.yaml:/app/workflow.yaml
    depends_on:
      - fetcher
